services:
  ros:
    user: itmo
    container_name: ros_itmo
    build:
      context: .
      args:
        - UID=${DOCKER_UID}
        - GID=${DOCKER_GID}
      dockerfile: ./Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTH}:${XAUTH}:rw
      - /dev/dri:/dev/dri
      - /dev/input:/dev/input 
      - ../:/home/itmo/labs
    env_file:
      - ./.env
    runtime: nvidia
    privileged: false 
    tty: true